### ISSUE TITLE
fluentd: how to use configuration overlays

### ISSUE THREAD

**Issue by berendt** [osism/documentation#354]
Document how to use configuration overlays to set custom inputs, outputs, filters, ...

Use as a concrete example the configuration of an additional output to an external log aggregator.

Related to SovereignCloudStack/issues#19

```
- name: Find custom fluentd input config files
  find:
    path: "{{ node_custom_config }}/fluentd/input"
    pattern: "*.conf"
  run_once: True
  register: find_custom_fluentd_inputs
  delegate_to: localhost
  when: common_services.fluentd.enabled | bool

- name: Find custom fluentd filter config files
  find:
    path: "{{ node_custom_config }}/fluentd/filter"
    pattern: "*.conf"
  run_once: True
  register: find_custom_fluentd_filters
  delegate_to: localhost
  when: common_services.fluentd.enabled | bool

- name: Find custom fluentd format config files
  find:
    path: "{{ node_custom_config }}/fluentd/format"
    pattern: "*.conf"
  run_once: True
  register: find_custom_fluentd_formats
  delegate_to: localhost
  when: common_services.fluentd.enabled | bool

- name: Find custom fluentd output config files
  find:
    path: "{{ node_custom_config }}/fluentd/output"
    pattern: "*.conf"
  run_once: True
  register: find_custom_fluentd_outputs
  delegate_to: localhost
  when: common_services.fluentd.enabled | bool
```
