### ISSUE TITLE
Ansible style guide: On which position to place the when condition

### ISSUE THREAD

**Issue by ra-rau** [osism/documentation#372]
Sometimes in the repositories the when condition is placed upper and sometimes it comes in the end of the code-block. For example: 
https://github.com/osism/ansible-collection-commons/blob/main/roles/resolvconf/tasks/configure-resolv.yml

example with when at the end:
```yaml
- name: "Archive existing {{ resolvconf_file }} file"
  become: true
  ansible.posix.synchronize:
    src: "/etc/resolv.conf"
    dest: "/etc/resolv.conf.{{ ansible_date_time.date }}"
    archive: true
  delegate_to: "{{ inventory_hostname }}"
  when: stat_resolvconf_file.stat.islnk is defined and not stat_resolvconf_file.stat.islnk
```

example with when in the beginning:
```yaml
- name: Restart systemd-resolved service
  become: true
  when: resolved_conf.changed  # noqa 503
  ansible.builtin.systemd:
    name: systemd-resolved
    daemon_reload: true
    state: restarted
```
