### ISSUE TITLE
Ansible style guide: Usage of collections or FQCN´s

### ISSUE THREAD

**Issue by ra-rau** [osism/documentation#374]
There are two ways to declare the ansible modules.
First way you can write it out like this one:

```yaml
- name: Configure netbox manufacturers
  netbox.netbox.netbox_manufacturer:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.value.name }}"
      slug: "{{ item.value.slug }}"
      description: "{{ item.value.description | default('') }}"
    state: present
  with_dict: "{{ netbox_data_manufacturers }}"
```

Or you can declare the collection like this:

```yaml  
collections:
    - netbox.netbox

  tasks:
    - name: Manage Discworld site
      netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: false
        data:
          name: Discworld
          slug: discworld
        state: present
```

We should declare one way that fits for us. We shouldn´t use both ways.
